name: Reusable — Add Labels (non-destructive)

on:
  workflow_call:
    inputs:
      technical_debt_color:
        type: string
        required: false
        default: "8b949e" # cinza
      technical_debt_desc:
        type: string
        required: false
        default: "Refatoração, dívidas técnicas, melhorias internas"
      uat_approved_color:
        type: string
        required: false
        default: "2ea043" # verde
      uat_approved_desc:
        type: string
        required: false
        default: "Homologado pelo cliente (User Acceptance Test)"
    secrets:
      GH_PROJECT_TOKEN:
        required: true

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure labels exist (create or update) — technical-debt
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          NAME: "technical-debt"
          COLOR: ${{ inputs.technical_debt_color }}
          DESC: ${{ inputs.technical_debt_desc }}
        run: |
          set -euo pipefail
          gh api -X PATCH "repos/$OWNER/$REPO/labels/$NAME" \
            -f new_name="$NAME" -f color="$COLOR" -f description="$DESC" \
          || gh api -X POST "repos/$OWNER/$REPO/labels" \
            -f name="$NAME" -f color="$COLOR" -f description="$DESC"
          echo "Synced label: $NAME"

      - name: Ensure labels exist (create or update) — uat-approved
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          NAME: "uat-approved"
          COLOR: ${{ inputs.uat_approved_color }}
          DESC: ${{ inputs.uat_approved_desc }}
        run: |
          set -euo pipefail
          gh api -X PATCH "repos/$OWNER/$REPO/labels/$NAME" \
            -f new_name="$NAME" -f color="$COLOR" -f description="$DESC" \
          || gh api -X POST "repos/$OWNER/$REPO/labels" \
            -f name="$NAME" -f color="$COLOR" -f description="$DESC"
          echo "Synced label: $NAME"
